name: standzclient
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  geolocator_web: ^2.2.0
  getwidget: ^4.0.0
  go_router: ^13.0.1
  http: ^1.1.2
  js: ^0.6.7
  provider: ^6.1.1
  url_launcher: ^6.2.3
  url_strategy: ^0.2.0
  webview_flutter_web: ^0.2.2+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
