import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/sellerhomepagewithmenupanel">
            SellerHomepagewithMenuPanel
          </Link>
        </li>
        <li>
          <Link to="/userprofile">UserProfile</Link>
        </li>
        <li>
          <Link to="/settingsnotificationsbuyer">
            SettingsNotificationsbuyer
          </Link>
        </li>
        <li>
          <Link to="/settingsprivacy">SettingsPrivacy</Link>
        </li>
        <li>
          <Link to="/buyerhistorywprofile">Buyerhistorywprofile</Link>
        </li>
        <li>
          <Link to="/chatwithprofile">ChatwithProfile</Link>
        </li>
        <li>
          <Link to="/signup">SignUp</Link>
        </li>
        <li>
          <Link to="/chat">Chat</Link>
        </li>
        <li>
          <Link to="/buyerchatwithmenu">BuyerchatwithMenu</Link>
        </li>
        <li>
          <Link to="/settingsnotifications">SettingsNotifications</Link>
        </li>
        <li>
          <Link to="/buyernotifwithmenu">BuyernotifwithMenu</Link>
        </li>
        <li>
          <Link to="/notification">Notification</Link>
        </li>
        <li>
          <Link to="/selleryourlandwithmenu">SellerYourLandwithMenu</Link>
        </li>
        <li>
          <Link to="/notificationwithmenu">NotificationwithMenu</Link>
        </li>
        <li>
          <Link to="/selleryourlandwithprofile">SellerYourlandwithProfile</Link>
        </li>
        <li>
          <Link to="/walletone">WalletOne</Link>
        </li>
        <li>
          <Link to="/selleryourland">SellerYourLand</Link>
        </li>
        <li>
          <Link to="/notificationwithprofile">NotificationwithProfile</Link>
        </li>
        <li>
          <Link to="/reccomendationswprofile">Reccomendationswprofile</Link>
        </li>
        <li>
          <Link to="/settingsaccount">SettingsAccount</Link>
        </li>
        <li>
          <Link to="/buyernotif">Buyernotif</Link>
        </li>
        <li>
          <Link to="/settingstheme">SettingsTheme</Link>
        </li>
        <li>
          <Link to="/settingsthemebuyer">SettingsThemebuyer</Link>
        </li>
        <li>
          <Link to="/settingslanguage">SettingsLanguage</Link>
        </li>
        <li>
          <Link to="/buyerchat">Buyerchat</Link>
        </li>
        <li>
          <Link to="/settingsprivacyone">SettingsPrivacyOne</Link>
        </li>
        <li>
          <Link to="/sellerjobvacancieswithmenu">
            SellerJobVacancieswithMenu
          </Link>
        </li>
        <li>
          <Link to="/chatwithmenu">ChatwithMenu</Link>
        </li>
        <li>
          <Link to="/userprofilebuyer">UserProfilebuyer</Link>
        </li>
        <li>
          <Link to="/sellerhistory">SellerHistory</Link>
        </li>
        <li>
          <Link to="/dailyattendance">DailyAttendance</Link>
        </li>
        <li>
          <Link to="/reccomendationswprofileone">
            ReccomendationswprofileOne
          </Link>
        </li>
        <li>
          <Link to="/sellerhistorywithprofile">SellerHistorywithProfile</Link>
        </li>
        <li>
          <Link to="/login">Login</Link>
        </li>
        <li>
          <Link to="/sellerjobvacancies">SellerJobVacancies</Link>
        </li>
        <li>
          <Link to="/sellerjobvacancieswithprofile">
            SellerJobVacancieswithProfile
          </Link>
        </li>
        <li>
          <Link to="/buyerjobvwiithmenu">Buyerjobvwiithmenu</Link>
        </li>
        <li>
          <Link to="/settingsprivacybuyer">SettingsPrivacybuyer</Link>
        </li>
        <li>
          <Link to="/settingslanguagebuyer">SettingsLanguagebuyer</Link>
        </li>
        <li>
          <Link to="/signout">SignOut</Link>
        </li>
        <li>
          <Link to="/dailyattendanceone">DailyAttendanceOne</Link>
        </li>
        <li>
          <Link to="/settingsaccountbuyer">SettingsAccountbuyer</Link>
        </li>
        <li>
          <Link to="/sellerhomepagewithprofile">SellerHomepagewithProfile</Link>
        </li>
        <li>
          <Link to="/buyeryourlandwithmenu">BuyerYourLandwithMenu</Link>
        </li>
        <li>
          <Link to="/reccomendationswmenu">Reccomendationswmenu</Link>
        </li>
        <li>
          <Link to="/buyerhomepagewithprofile">Buyerhomepagewithprofile</Link>
        </li>
        <li>
          <Link to="/buyerhomepagepanel">BuyerhomepagePanel</Link>
        </li>
        <li>
          <Link to="/buyerjobvwprofile">Buyerjobvwprofile</Link>
        </li>
        <li>
          <Link to="/sellerhomepage">SellerHomepage</Link>
        </li>
        <li>
          <Link to="/reccomendations">Reccomendations</Link>
        </li>
        <li>
          <Link to="/buyerhomepagewithmenupanel">
            BuyerhomepagewithMenuPanel
          </Link>
        </li>
        <li>
          <Link to="/buyernotifwithprofile">BuyernotifwithProfile</Link>
        </li>
        <li>
          <Link to="/reccomendationswmenuone">ReccomendationswmenuOne</Link>
        </li>
        <li>
          <Link to="/buyerhomepage">Buyerhomepage</Link>
        </li>
        <li>
          <Link to="/buyerjobv">Buyerjobv</Link>
        </li>
        <li>
          <Link to="/buyerhistorywithmenupanel">BuyerhistorywithMenuPanel</Link>
        </li>
        <li>
          <Link to="/buyerhistory">Buyerhistory</Link>
        </li>
        <li>
          <Link to="/sellerhistorywithmenupanel">
            SellerHistorywithMenuPanel
          </Link>
        </li>
        <li>
          <Link to="/buyerchatwithprofile">BuyerchatwithProfile</Link>
        </li>
        <li>
          <Link to="/wallet">Wallet</Link>
        </li>
        <li>
          <Link to="/reccomendationsone">ReccomendationsOne</Link>
        </li>
        <li>
          <Link to="/sellerhomepagepanel">SellerHomepagePanel</Link>
        </li>
        <li>
          <Link to="/buyeryourland">BuyerYourLand</Link>
        </li>
        <li>
          <Link to="/buyeryourlandwithprofile">BuyerYourLandwithProfile</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
